wholeslidedata:
  default:
    image_backend: asap
    seed: 123
    yaml_source: data.yml

    label_map:
      tumor: 1
      lymphocytes: 2
      stroma: 3

    label_sampler:
      attribute: OrderedLabelSampler

    annotation_sampler:
      attribute: OrderedAnnotationSampler

    point_sampler:
      attribute: RandomPointSampler
      buffer: -142

    batch_shape:
      batch_size: 1
      shape: [ 64, 64,3 ]
      spacing: [ 0.5 ]
      y_shape: [ 64, 64, 3 ]

    batch_callbacks:
      - module: wholeslidedata.accessories.albumentations.callbacks
        attribute: AlbumentationsAugmentationsCallback
        augmentations:
          - RandomRotate90:
              p: 0.5
          - Flip:
              p: 0.5
          - HueSaturationValue:
              hue_shift_limit: 0.2
              sat_shift_limit: 0.3
              val_shift_limit: 0.2
              p: 0.5
          - GridDistortion:
              p: 1.0
          - RandomBrightnessContrast:
              p: 0.4

    sample_callbacks:
      - module: wholeslidedata.samplers.callbacks
        attribute: OneHotEncoding
        labels: ${wholeslidedata:labels}

