_target_: src.datamodules.wsi_datamodule.WsiDataModule

steps_per_epoch: 1000
num_classes: 3
num_workers: 6
pin_memory: False
context: spawn

user_train_config: ${original_work_dir}/configs/wsd_configs/user_config.yml
# Temporary solution for using WholeSlideData. This should be ported to Hydra.
user_val_config: ${original_work_dir}/configs/wsd_configs/user_config.yml
# Temporary solution for using WholeSlideData. This should be ported to Hydra.
user_test_config: ${original_work_dir}/configs/wsd_configs/user_config.yml
# Temporary solution for using WholeSlideData. This should be ported to Hydra.
